name: Teammate
version: '${version}'
main: io.teamplayer.teammate.Teammate
api-version: '1.20'
dependencies:
  server:
    AdvancedVanish:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
    GriefPrevention:
      required: false
      load: BEFORE