name: TeamExtensions
version: '${version}'
main: io.teamplayer.teamextensions.TeamExtensions
api-version: '1.20'
dependencies:
  server:
    AdvancedVanish:
      required: true
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE